### ISSUE TITLE
[codelab] missing package 3. Add a navigation drawer

### ISSUE THREAD

**Issue by slin004** [material-components/material-components-web-codelabs#54]
try to follow tutorial but webpack compile failed

WHERE:
```
@https://codelabs.developers.google.com/codelabs/mdc-102-web/#2
3. Add a navigation drawer
```

ERROR:
```
ERROR in ./app.scss
    Module build failed:
      @include mdc-typography-baseline-top($mdc-list-item-primary-text-baseline-height_);
              ^
          No mixin named mdc-typography-baseline-top
          in node_modules/@material/list/mdc-list.scss (line 109, column 12)
     @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./app.scss
```

manual install
```
npm install @material/typography
```

**Comment by kfranqueiro** [comment]
This is probably due to conflicting versions of MDC Web dependencies. We've since corrected the codelab instructions to ensure that we're instructing a consistent version to be used across 101, 102, and 103. (All `npm install` commands in these codelabs now specify `@0.35.0` after the package.)

See #52 for more information. I'm going to close this since it seems like a very similar issue.
