### ISSUE TITLE
[codelab] <MDC-102: mdc-list failing to compile>

### ISSUE THREAD

**Issue by kbrunet** [material-components/material-components-web-codelabs#59]
In app.scss, `@import "@material/list/mdc-list";` causes a compile failure:

```
ERROR in ./app.scss
    Module build failed: 
      @include mdc-typography-baseline-top($mdc-list-item-primary-text-baseline-height_);
              ^
          No mixin named mdc-typography-baseline-top
          in node_modules/@material/list/mdc-list.scss (line 109, column 12)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.scss

```

**Comment by kfranqueiro** [comment]
FYI, we recently updated these codelabs to always specify the version of the package to install in order to match the version of MDC Web at the time the codelabs were written. If you ran any `npm install @material/...` commands without specifying the package version, a version mismatch could be causing this error.

I would suggest one of the following options:

* Restart the codelab
* Edit any `@material` packages in your `package.json` to reference version `^0.35.0`, then remove the `node_modules` folder and run `npm install` again

Sorry for the inconvenience.

**Comment by kfranqueiro** [comment]
Closing this given no further response. Please let us know if you still encounter issues.
